tasks:
    - name: install_postgres
      before: |
          docker network create pg-network
          docker volume create --name=dtc_postgres_volume_local -d local
          docker run -it -e POSTGRES_USER="root" -e POSTGRES_PASSWORD="root" -e POSTGRES_DB="ny_taxi" \
          -v dtc_postgres_volume_local:/var/lib/postgresql/data \
          -p 5432:5432 --network=pg-network \
          --name pg_database postgres:13
    - name: install_pgadmin
      before: |
        docker volume create --name=dtc_pgadmin_volume_local -d local
        docker run -it -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" -e PGADMIN_DEFAULT_PASSWORD="root" -v dtc_pgadmin_volume_local:/var/lib/pgadmin -p 5050:5050 --network=pg-network --name pgadmin dpage/pgadmin4 
