tasks:
    - name: install_postgres
      before: |
          docker network create pg-network
          docker volume create --name=dtc_postgres_volume_local -d local
          docker run -it -e POSTGRES_USER="root" -e POSTGRES_PASSWORD="root" -e POSTGRES_DB="ny_taxi" \
          -v ./nyc_taxi_postgres_data:/var/lib/postgresql/data \
          -p 5432:5432 --network=pg-network \
          --name pg_database postgres:13
    - name: install_pgadmin
      before: |
        docker run -it -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" -e PGADMIN_DEFAULT_PASSWORD="root" -p 8080:80 --network=pg-network --name pgadmin dpage/pgadmin4 